### ISSUE TITLE
Stage 1 is a no-op

### ISSUE THREAD

**Issue by sweeneychris** [vrdabomb5717/jenkins_traub#1]
https://github.com/vrdabomb5717/jenkins_traub/blob/master/jenkins_traub.py#L61

None of the returned variables are used... what is this stage supposed to be doing?

**Comment by vrdabomb5717** [comment]
You're right, this _is_ unused. I need to go back to the paper and figure out what's going on here. The downside of not committing often is that I don't quite know when this was introduced, and why I did it this way.
